### ISSUE TITLE
Feature request: support for pydantic types

### ISSUE THREAD

**Issue by lsorber** [timothycrosley/hypothesis-auto#10]
Thank you for the really nice library!

This would be such an awesome feature to have:

```python
from hypothesis_auto import auto_test
from pydantic import BaseModel, ValidationError, validator


class UserModel(BaseModel):
    name: str
    password1: str
    password2: str

    @validator('name')
    def name_must_contain_space(cls, v):
        if ' ' not in v:
            raise ValueError('must contain a space')
        return v.title()


def create_user(user: UserModel):
    print(user)
    assert True


print(UserModel(name='samuel colvin', password1='zxcvbn', password2='zxcvbn'))
auto_test(create_user)  # Throws `pydantic.ValidationError` :-(
```

**Comment by Zac-HD** [comment]
See https://github.com/samuelcolvin/pydantic/issues/1032 - once upstream sets the signature for introspection, Hypothesis will pick it up with our existing features.  So there's nothing for `hypothesis-auto` to do but wait!

**Comment by Zac-HD** [comment]
:tada: 

From the next release of `pydantic`, this will 'just work' (tm).

**Comment by pquentin** [comment]
This is something I'd love to use. I use FastAPI and would like hypothesis-auto to generate pydantic models, in order to see where my code makes wrong assumptions about possible user input.

However, running the script above with hypothesis 5.8.0, hypothesis-auto 1.1.4 and pydantic master (1.5a1), I get this error:

```
name='Samuel Colvin' password1='zxcvbn' password2='zxcvbn'
/.../site-packages/hypothesis/strategies/_internal/strategies.py:273: NonInteractiveExampleWarning: The `.example()` method is good for exploring strategies, but should only be used interactively.  We recommend using `@given` for tests - it performs better, saves and replays failures to avoid flakiness, and reports minimal examples. (strategy: builds(pass_along_variables))
  NonInteractiveExampleWarning,
Traceback (most recent call last):
  File "t.py", line 23, in <module>
    auto_test(create_user)  # Throws `pydantic.ValidationError` :-(
  File "/.../site-packages/hypothesis_auto/tester.py", line 200, in auto_test
    **kwargs
  File "/.../site-packages/hypothesis_auto/tester.py", line 161, in auto_test_cases
    for parameters in auto_parameters(auto_function_, *args, auto_limit_=auto_limit_, **kwargs):
  File "/.../site-packages/hypothesis_auto/tester.py", line 126, in auto_parameters
    yield strategy.example()
  File "/.../site-packages/hypothesis/strategies/_internal/strategies.py", line 314, in example
    example_generating_inner_function()
  File "/.../site-packages/hypothesis/strategies/_internal/strategies.py", line 302, in example_generating_inner_function
    @settings(
  File "/.../site-packages/hypothesis/core.py", line 1090, in wrapped_test
    raise the_error_hypothesis_found
  File "/.../site-packages/pydantic-1.5a1-py3.6.egg/pydantic/main.py", line 324, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 3 validation errors for UserModel
name
  field required (type=value_error.missing)
password1
  field required (type=value_error.missing)
password2
  field required (type=value_error.missing)
```

I also get the same output with pydantic 1.4.

Is there anything I'm missing here? Thanks!

**Comment by Zac-HD** [comment]
Turns out that for classes, Hypothesis calculates the `required_args` based on `__init__` rather than the `__signature__`.  We'll have a patch out fixing that shortly!

We don't automatically filter arguments out on `ValidationError` though, so in this case you'll need to pass an explicit strategy like `st.builds(UserModel, name=st.from_regex(".* .*")`.

There's probably scope to do something fancier with automatic validation-based filtering though, if you're keen...

**Comment by pquentin** [comment]
Thanks for the pull request! The above script now prints the following:

```
.../site-packages/hypothesis/strategies/_internal/strategies.py:268: NonInteractiveExampleWarning: The `.example()` method is good for exploring strategies, but should only be used interactively.  We recommend using `@given` for tests - it performs better, saves and replays failures to avoid flakiness, and reports minimal examples. (strategy: builds(pass_along_variables))
  warnings.warn(
name='Samuel Colvin' password1='zxcvbn' password2='zxcvbn'
Traceback (most recent call last):
  File "t.py", line 23, in <module>
    auto_test(create_user)  # Throws `pydantic.ValidationError` :-(
  File ".../site-packages/hypothesis_auto/tester.py", line 194, in auto_test
    for test_case in auto_test_cases(
  File ".../site-packages/hypothesis_auto/tester.py", line 161, in auto_test_cases
    for parameters in auto_parameters(auto_function_, *args, auto_limit_=auto_limit_, **kwargs):
  File ".../site-packages/hypothesis_auto/tester.py", line 126, in auto_parameters
    yield strategy.example()
  File ".../site-packages/hypothesis/strategies/_internal/strategies.py", line 314, in example
    example_generating_inner_function()
  File ".../site-packages/hypothesis/strategies/_internal/strategies.py", line 302, in example_generating_inner_function
    @settings(
  File ".../site-packages/hypothesis/core.py", line 969, in wrapped_test
    processed_args = process_arguments_to_given(
  File ".../site-packages/hypothesis/core.py", line 415, in process_arguments_to_given
    search_strategy.validate()
  File ".../site-packages/hypothesis/strategies/_internal/strategies.py", line 377, in validate
    self.do_validate()
  File ".../site-packages/hypothesis/strategies/_internal/collections.py", line 39, in do_validate
    s.validate()
  File ".../site-packages/hypothesis/strategies/_internal/strategies.py", line 377, in validate
    self.do_validate()
  File ".../site-packages/hypothesis/strategies/_internal/strategies.py", line 637, in do_validate
    self.mapped_strategy.validate()
  File ".../site-packages/hypothesis/strategies/_internal/strategies.py", line 377, in validate
    self.do_validate()
  File ".../site-packages/hypothesis/strategies/_internal/lazy.py", line 118, in do_validate
    w.validate()
  File ".../site-packages/hypothesis/strategies/_internal/strategies.py", line 377, in validate
    self.do_validate()
  File ".../site-packages/hypothesis/strategies/_internal/strategies.py", line 637, in do_validate
    self.mapped_strategy.validate()
  File ".../site-packages/hypothesis/strategies/_internal/strategies.py", line 377, in validate
    self.do_validate()
  File ".../site-packages/hypothesis/strategies/_internal/collections.py", line 39, in do_validate
    s.validate()
  File ".../site-packages/hypothesis/strategies/_internal/strategies.py", line 377, in validate
    self.do_validate()
  File ".../site-packages/hypothesis/strategies/_internal/lazy.py", line 118, in do_validate
    w.validate()
  File ".../site-packages/hypothesis/strategies/_internal/strategies.py", line 377, in validate
    self.do_validate()
  File ".../site-packages/hypothesis/strategies/_internal/strategies.py", line 637, in do_validate
    self.mapped_strategy.validate()
  File ".../site-packages/hypothesis/strategies/_internal/strategies.py", line 377, in validate
    self.do_validate()
  File ".../site-packages/hypothesis/strategies/_internal/lazy.py", line 118, in do_validate
    w.validate()
  File ".../site-packages/hypothesis/strategies/_internal/strategies.py", line 377, in validate
    self.do_validate()
  File ".../site-packages/hypothesis/strategies/_internal/collections.py", line 39, in do_validate
    s.validate()
  File ".../site-packages/hypothesis/strategies/_internal/strategies.py", line 377, in validate
    self.do_validate()
  File ".../site-packages/hypothesis/strategies/_internal/strategies.py", line 637, in do_validate
    self.mapped_strategy.validate()
  File ".../site-packages/hypothesis/strategies/_internal/strategies.py", line 377, in validate
    self.do_validate()
  File ".../site-packages/hypothesis/strategies/_internal/collections.py", line 39, in do_validate
    s.validate()
  File ".../site-packages/hypothesis/strategies/_internal/strategies.py", line 377, in validate
    self.do_validate()
  File ".../site-packages/hypothesis/strategies/_internal/lazy.py", line 118, in do_validate
    w.validate()
  File ".../site-packages/hypothesis/strategies/_internal/strategies.py", line 378, in validate
    self.is_empty
  File ".../site-packages/hypothesis/strategies/_internal/strategies.py", line 125, in accept
    recur(self)
  File ".../site-packages/hypothesis/strategies/_internal/strategies.py", line 121, in recur
    mapping[strat] = getattr(strat, calculation)(recur)
  File ".../site-packages/hypothesis/strategies/_internal/deferred.py", line 80, in calc_is_empty
    return recur(self.wrapped_strategy)
  File ".../site-packages/hypothesis/strategies/_internal/deferred.py", line 43, in wrapped_strategy
    result = self.__definition()
  File ".../site-packages/hypothesis/strategies/_internal/core.py", line 1335, in <lambda>
    lambda thing: deferred(lambda: _from_type(thing)),
  File ".../site-packages/hypothesis/strategies/_internal/core.py", line 1449, in _from_type
    raise ResolutionFailed(
hypothesis.errors.ResolutionFailed: Could not resolve <class '__main__.UserModel'> to a strategy; consider using register_type_strategy
```

Sorry, this is the first time I use pydantic, I don't know what to do with this error.

> There's probably scope to do something fancier with automatic validation-based filtering though, if you're keen...

I guess it would be interesting to explore, though for my current use case there's not much validation going on.

**Comment by Zac-HD** [comment]
I *think* that's driven by the weird internals of hypothesis-auto - it uses the example() method is ways we recommend against (hence the warning at the top of that traceback), but https://github.com/HypothesisWorks/hypothesis/pull/2344 still needs some review and polish...

It should work if you write an explicit test with the given decorator though!

**Comment by Zac-HD** [comment]
OK, the PR has been updated to fix that too and now [released as Hypothesis 5.8.3](https://hypothesis.readthedocs.io/en/latest/changes.html#v5-8-3) :smile:

**Comment by samuelcolvin** [comment]
is this now fixed? It looks like hypothesis and inspect `__signature__` and pydantic now includes `__signature__` - surely everything should be sweetness and light?

**Comment by pquentin** [comment]
I just tested again, and the following snippet runs as is with the latest version of hypothesis, hypothesis-auto and pydantic:

```python3
from hypothesis import strategies as st
from hypothesis_auto import auto_test
from pydantic import BaseModel, validator


class UserModel(BaseModel):
    name: str
    password1: str
    password2: str

    @validator("name")
    def name_must_contain_space(cls, v):
        if " " not in v:
            raise ValueError("must contain a space")
        return v.title()


def create_user(user: UserModel):
    print(user)
    assert True


auto_test(create_user, user=st.builds(UserModel, name=st.from_regex(".* .*")))
```

Thanks! @lsorber This issue can be closed.

**Comment by lsorber** [comment]
It's pretty awesome that this works now, nice work all!

**Comment by samuelcolvin** [comment]
On the pydantic side it was mostly @MrMrRobat finding a way to implement the signature.

Well done, all.
