### ISSUE TITLE
Hypothesis dependency <6.0.0 error

### ISSUE THREAD

**Issue by isidroas** [timothycrosley/hypothesis-auto#24]
```
$ python --version
Python 3.12.3+
$ pip install hypothesis-auto
$ python -c 'import hypothesis_auto'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/hypothesis-auto/venv/lib/python3.12/site-packages/hypothesis_auto/__init__.py", line 1, in <module>
    from hypothesis_auto.tester import (
  File "/tmp/hypothesis-auto/venv/lib/python3.12/site-packages/hypothesis_auto/tester.py", line 16, in <module>
    from hypothesis import given, settings
  File "/tmp/hypothesis-auto/venv/lib/python3.12/site-packages/hypothesis/__init__.py", line 61, in <module>
    run()
  File "/tmp/hypothesis-auto/venv/lib/python3.12/site-packages/hypothesis/entry_points.py", line 61, in run
    for entry in get_entry_points():  # pragma: no cover
  File "/tmp/hypothesis-auto/venv/lib/python3.12/site-packages/hypothesis/entry_points.py", line 32, in get_entry_points
    yield from importlib_metadata.entry_points().get("hypothesis", [])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'get'
```

I have narrowed down the error further. It can be replicated without this library:

```
$ pip install 'hypothesis<6'
$ python -c 'import hypothesis'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/hypothesis/venv/lib/python3.12/site-packages/hypothesis/__init__.py", line 61, in <module>
    run()
  File "/tmp/hypothesis/venv/lib/python3.12/site-packages/hypothesis/entry_points.py", line 61, in run
    for entry in get_entry_points():  # pragma: no cover
  File "/tmp/hypothesis/venv/lib/python3.12/site-packages/hypothesis/entry_points.py", line 32, in get_entry_points
    yield from importlib_metadata.entry_points().get("hypothesis", [])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'get'

$ pip list
Package          Version
---------------- -------
attrs            24.2.0
hypothesis       5.49.0
pip              24.0
sortedcontainers 2.4.0
```

**Comment by isidroas** [comment]
I tried with `poetry build` but it fails with an error related to `pyyaml=6`.

Could someone show me the output of `pip freeze` ?
